project_id = "psuvnvqvspqibsezcrny"

[functions.save-to-gallery]
verify_jwt = false

[functions.send-telegram-notification]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.protalk-ai]
verify_jwt = false
